# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIIdentifyResult.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_identifyResult(object):
    def setupUi(self, identifyResult):
        identifyResult.setObjectName("identifyResult")
        identifyResult.resize(643, 592)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(identifyResult)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = CollapsibleSplitter(identifyResult)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tree_result = QtWidgets.QTreeWidget(self.splitter)
        self.tree_result.setIndentation(20)
        self.tree_result.setColumnCount(1)
        self.tree_result.setObjectName("tree_result")
        self.tree_result.headerItem().setText(0, "1")
        self.tree_result.header().setVisible(False)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tlb_result = QtWidgets.QTableWidget(self.layoutWidget)
        self.tlb_result.setObjectName("tlb_result")
        self.tlb_result.setColumnCount(0)
        self.tlb_result.setRowCount(0)
        self.verticalLayout.addWidget(self.tlb_result)
        self.verticalLayout_2.addWidget(self.splitter)
        self.lbl_identifyInfo = QtWidgets.QLabel(identifyResult)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_identifyInfo.sizePolicy().hasHeightForWidth())
        self.lbl_identifyInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.lbl_identifyInfo.setFont(font)
        self.lbl_identifyInfo.setObjectName("lbl_identifyInfo")
        self.verticalLayout_2.addWidget(self.lbl_identifyInfo)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(identifyResult)
        QtCore.QMetaObject.connectSlotsByName(identifyResult)

    def retranslateUi(self, identifyResult):
        _translate = QtCore.QCoreApplication.translate
        identifyResult.setWindowTitle(_translate("identifyResult", "Form"))
        self.label.setText(_translate("identifyResult", "坐标："))
        self.lbl_identifyInfo.setText(_translate("identifyResult", "TextLabel"))
from widgets.CollapsibleSplitter import CollapsibleSplitter
