# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UILogView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmLogView(object):
    def setupUi(self, frmLogView):
        frmLogView.setObjectName("frmLogView")
        frmLogView.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(frmLogView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_log = QtWidgets.QPlainTextEdit(frmLogView)
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName("txt_log")
        self.verticalLayout.addWidget(self.txt_log)

        self.retranslateUi(frmLogView)
        QtCore.QMetaObject.connectSlotsByName(frmLogView)

    def retranslateUi(self, frmLogView):
        _translate = QtCore.QCoreApplication.translate
        frmLogView.setWindowTitle(_translate("frmLogView", "Form"))
