# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/地理学院.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mapCanvas = QgsMapCanvas(self.centralwidget)
        self.mapCanvas.setGeometry(QtCore.QRect(80, 130, 451, 271))
        self.mapCanvas.setObjectName("mapCanvas")
        self.tocView = QgsLayerTreeView(self.centralwidget)
        self.tocView.setGeometry(QtCore.QRect(670, 190, 120, 80))
        self.tocView.setObjectName("tocView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mainToolbar = QtWidgets.QToolBar(MainWindow)
        self.mainToolbar.setIconSize(QtCore.QSize(32, 32))
        self.mainToolbar.setObjectName("mainToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainToolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
from qgis.gui import QgsLayerTreeView, QgsMapCanvas
import icons_rc
